PARTICLE_ENABLED   = False
PARTICLE_FORCE     = 5.0
PARTICLE_GRAVITY_Y = -9.8
PARTICLE_FADE_RATE = 0.5
PARTICLE_DRAG      = 0.98
PARTICLE_DT_MAX    = 0.05

PARTICLE_SPRING_K      = 6.0
PARTICLE_DAMPING       = 0.96
PARTICLE_IMPULSE_FORCE = 6.0
PARTICLE_VEL_CLAMP     = 50.0

PARTICLE_KEY_TOGGLE    = 'V'
PARTICLE_KEY_INTERACT  = 'X'
PARTICLE_KEY_IMPULSE   = 'Z'
