REGION_RAMP_SHAPES = ('linear', 'spherical', 'box')
REGION_RAMP_DEFAULT_SHAPE = 'spherical'
REGION_RAMP_AXIS_DEFAULT = 0
REGION_RAMP_EDGE_DEFAULT = 0.05
REGION_RAMP_LUT_N = 256
REGION_RAMP_MULT_HANDLES = 3
REGION_RAMP_INTENSITY_HANDLES = 3
