from process.component.noise import NOISE_TYPES

STARTUP_DEFAULTS = 'plugin_default'

VOLUME_SHAPE = 'sphere'

DEFAULT_VISIBILITY = False
DEFAULT_ACTIVE = False

DEFAULT_NOISE_TYPE: str = 'curl'

DEFAULT_NOISE_RAMP_SHAPE = 'box'

DEFAULT_NOISE_RAMP_AXIS = 1

DEFAULT_NOISE_THRESHOLD = 0.5

DEFAULT_NOISE_GAIN = 0.35

DEFAULT_NOISE_FREQ = 2.5

DEFAULT_NOISE_SPEED = 0.6

DEFAULT_NOISE_WIDTH = 0.75

DEFAULT_NOISE_OCTAVES = 30

DEFAULT_NOISE_SIZE_VAR = 0.0

DEFAULT_NOISE_SIZE_VAR_EDGE_MIN = 0.0

DEFAULT_NOISE_MIN_OPACITY = 0.0

DEFAULT_NOISE_SIZE_MIN = 0.0

DEFAULT_NOISE_RAMP_EDGE = 0.05

DEFAULT_NOISE_REGION_SOFTNESS = 1.5

NOISE_NOISE_TYPES: tuple[str, ...] = NOISE_TYPES
NOISE_RAMP_SHAPES: tuple[str, ...] = ('linear', 'spherical', 'box')
NOISE_GAIN_RANGE    = (0.0, 2.0)
NOISE_FREQ_RANGE    = (0.1, 10.0)
NOISE_SPEED_RANGE   = (0.0, 3.0)
NOISE_WIDTH_RANGE   = (0.0, 1.0)
NOISE_OCTAVES_RANGE = (1, 64)
NOISE_SIZE_VAR_RANGE = (0.0, 1.0)

NOISE_KEY_TRIGGER       = 'X'
NOISE_KEY_CYCLE_TYPE    = 'T'
NOISE_KEY_THRESHOLD_UP   = 'O'
NOISE_KEY_THRESHOLD_DOWN = 'I'

NOISE_THRESHOLD_STEP    = 0.05

from configs.settings_annot import ANNOT_ANIM_DURATION
KEYFRAME_MOVE_DURATION = ANNOT_ANIM_DURATION

STARTUP_VISIBILITY = False
STARTUP_ACTIVE = False

STARTUP_NOISE_REGION_CENTER = (0.0, 0.0, 0.0)
STARTUP_NOISE_REGION_SIZE   = (1.0, 1.0, 1.0)

STARTUP_NOISE_DT_MAX = 0.05

STARTUP_NOISE_CURVE_LUT_N = 256
STARTUP_NOISE_CURVE_HANDLES = 3

STARTUP_NOISE_RAMP_MULT_HANDLES = 3
STARTUP_NOISE_RAMP_MULT_DEFAULT = (
    (0.0, 1.0, 'ease'), (0.5, 1.0, 'ease'), (1.0, 1.0, 'ease'),
)
