STARTUP_DEFAULTS = 'plugin_default'

VOLUME_SHAPE = 'cube'

DEFAULT_VISIBILITY = False
DEFAULT_ACTIVE = False

DEFAULT_CROP_INVERT = False

DEFAULT_CROP_REGION_SOFTNESS = 0.02

CROP_KEY_TRIGGER = 'X'
CROP_KEY_INVERT  = 'T'

from configs.settings_annot import ANNOT_ANIM_DURATION
KEYFRAME_MOVE_DURATION = ANNOT_ANIM_DURATION

STARTUP_VISIBILITY = False
STARTUP_ACTIVE = False

STARTUP_CROP_REGION_CENTER = (0.0, 0.0, 0.0)
STARTUP_CROP_REGION_SIZE   = (1.0, 1.0, 1.0)

POINTCLOUD_SUPPORTED = True
