POLYGON_MIN_VERTS = 3

POLYGON_EXTRUDE_INIT_RATIO = 0.25

POLYGON_DEPTH_MIN = 0.001

POLYGON_DRAW_LINE_COLOR   = '#4dd0ff'
POLYGON_DRAW_RUBBER_COLOR = '#ffd24d'
POLYGON_DRAW_VERT_COLOR   = '#4dd0ff'
POLYGON_DRAW_LINE_WIDTH   = 2
POLYGON_DRAW_VERT_RADIUS  = 4

POLYGON_KEY_COMPLETE    = 'Return'
POLYGON_KEY_COMPLETE_KP = 'Enter'
POLYGON_KEY_UNDO        = 'Backspace'
