KEY_PLAY_PAUSE = 'Space'
KEY_PREV_FRAME = 'Left'
KEY_NEXT_FRAME = 'Right'
KEY_FIRST_FRAME = 'Up'
KEY_LAST_FRAME = 'Down'
KEY_QUIT = 'Escape'

RESET_CAM = 'Alt+Shift+R'
TURNTABLE_TOGGLE = 'NumDecimal'

ORTHO_CAM_FRONT  = 'F5'
ORTHO_CAM_BACK   = 'F6'
ORTHO_CAM_LEFT   = 'F7'
ORTHO_CAM_RIGHT  = 'F8'
ORTHO_CAM_TOP    = 'F9'
ORTHO_CAM_BOTTOM = 'F10'

OBJECT_ISOLATE_KEYS = (
    'Alt+1', 'Alt+2', 'Alt+3', 'Alt+4',
    'Alt+5', 'Alt+6', 'Alt+7', 'Alt+8',
    'Alt+9',
)

RESET_ALL = 'Ctrl+Home'

RECORD_TOGGLE = 'Ctrl+R'

OBJECT_RESET = 'Alt+R'

SCREENSHOT = 'QuoteLeft'

SOLO_TOGGLE = 'S'

SLICE_RATIO_UP = 'Ctrl+]'
SLICE_RATIO_DOWN = 'Ctrl+['
SLICE_RATIO_RESET = 'Ctrl+Backslash'

SPLAT_SIZE_UP = ']'
SPLAT_SIZE_DOWN = '['
SPLAT_SIZE_RESET = 'Backslash'

CAM_KEY_ADD = 'Alt+Shift+A'
CAM_KEY_REMOVE = 'Alt+Shift+D'
CAM_KEY_CLEAR = 'Alt+Shift+Delete'
CAM_KEY_TOGGLE = 'Alt+Shift+P'
CAM_KEY_GOTO_NEXT = 'Alt+Shift+PageDown'
CAM_KEY_GOTO_PREV = 'Alt+Shift+PageUp'

OBJ_KEY_ADD = 'Alt+A'
OBJ_KEY_REMOVE = 'Alt+D'
OBJ_KEY_CLEAR = 'Alt+Delete'
OBJ_KEY_GOTO_NEXT = 'Alt+PageDown'
OBJ_KEY_GOTO_PREV = 'Alt+PageUp'
OBJ_KEY_TOGGLE = 'Alt+P'

GLOBAL_KEY_ADD = 'A'
GLOBAL_KEY_REMOVE = 'D'
GLOBAL_KEY_CLEAR = 'Ctrl+Delete'
GLOBAL_KEY_GOTO_NEXT = 'Ctrl+PageDown'
GLOBAL_KEY_GOTO_PREV = 'Ctrl+PageUp'
GLOBAL_KEY_TOGGLE = 'P'

DELETE_SELECTED = 'Delete'

TOGGLE_OVERLAY = 'F1'
TOGGLE_PLUGIN_HELP = 'F2'
TOGGLE_WORLD_ROT = 'Tab'
TOGGLE_MESH = 'Apostrophe'
TOGGLE_COLORMAP = 'C'
TOGGLE_DEPTH_OCCLUSION = 'B'

TOGGLE_CORNER_BRACKET = 'Shift+B'

THEME_CYCLE = 'Ctrl+B'
TOGGLE_LOGS = 'Period'
TOGGLE_FOG = 'F'
TOGGLE_SEQUENCE_OVERLAY = 'Comma'
TOGGLE_ALL_OVERLAYS = 'Slash'
TOGGLE_ATTR_OVERLAY = 'Semicolon'

TOGGLE_PREVIEW_OVERLAYS = 'U'

MODE_DEFAULT = 'Q'
MODE_NORMAL = '1'
MODE_POINT = '2'
MODE_ANISO = '3'
MODE_OPACITY = '4'
MODE_HIT_COUNT = '5'
MODE_ACCUMULATION = '6'
MODE_SCALE = '7'

MODE_SH = ''
MODE_GL_POINTS = '8'
MODE_ROTATION = '9'
MODE_MEDIAN_DEPTH = '0'
