from configs.settings_color import (
    SELECTED_COLOR, DESELECTED_COLOR, LOCKED_COLOR,
)
__all__: list[str] = [
    'SELECTED_COLOR', 'DESELECTED_COLOR', 'LOCKED_COLOR',
    'REGION_LINE_ALPHA', 'REGION_LINE_WIDTH', 'REGION_HOVER_LINE_WIDTH',
    'REGION_CORNER_DRAW_PX', 'REGION_FACE_ALPHA',
    'REGION_FACE_ALPHA_SELECTED',
    'SELECTED_LINE_WIDTH', 'LOCKED_LINE_WIDTH', 'LOCKED_ALPHA',
    'SELECTION_CORNER_RATIO',
    'REGION_CORNER_BRACKETS', 'OBJECT_CORNER_BRACKETS',
    'STARTUP_REGION_CORNER_BRACKETS', 'LOCK_BRACKET',
]
# -- Region Box Wireframe / Face --
REGION_LINE_ALPHA: float          = 0.65
REGION_LINE_WIDTH: int          = 2
REGION_HOVER_LINE_WIDTH: int    = 2
REGION_CORNER_DRAW_PX: int      = 6
REGION_FACE_ALPHA: float          = 0.0
REGION_FACE_ALPHA_SELECTED: float = 0.1
# -- Selection / Lock Box Style --
SELECTED_LINE_WIDTH: int        = 1
LOCKED_LINE_WIDTH: int          = 1
LOCKED_ALPHA: float               = 0.4
SELECTION_CORNER_RATIO: float     = 0.18
REGION_CORNER_BRACKETS: bool = False
OBJECT_CORNER_BRACKETS: bool = False
STARTUP_REGION_CORNER_BRACKETS: bool = False
LOCK_BRACKET: bool = False
