from configs.settings_style import (
    SELECTED_COLOR, DESELECTED_COLOR, LOCKED_COLOR,
    REGION_CORNER_DRAW_PX, REGION_FACE_ALPHA, REGION_FACE_ALPHA_SELECTED,
    REGION_HOVER_LINE_WIDTH, REGION_LINE_ALPHA, REGION_LINE_WIDTH,
)

TOOL_NONE      = ''
TOOL_TRANSLATE = 'translate'
TOOL_ROTATE    = 'rotate'
TOOL_SCALE     = 'scale'

REGION_VOLUME_AXIS_COLOR_X = '#ff4d4d'
REGION_VOLUME_AXIS_COLOR_Y = '#4dff7a'
REGION_VOLUME_AXIS_COLOR_Z = '#4d8dff'

REGION_VOLUME_SCREEN_LEN_PX     = 160
REGION_VOLUME_LINE_WIDTH        = 9
REGION_VOLUME_HOVER_LINE_WIDTH  = 12

REGION_VOLUME_PICK_TOL_PX       = 32
REGION_VOLUME_ROTATE_TOL_RATIO  = 0.22

REGION_VOLUME_TRACKBALL_RAD_PER_PX = 0.01

REGION_VOLUME_SCALE_HANDLE_SIZE_PX  = 22
REGION_VOLUME_SCALE_CENTER_BOX_PX   = 18
REGION_VOLUME_HANDLE_BORDER_PX      = 2
REGION_VOLUME_HANDLE_HOVER_BORDER_PX = 3

REGION_VOLUME_CLICK_TOL_PX      = 6

REGION_VOLUME_HOVER_COLOR       = SELECTED_COLOR

REGION_VOLUME_HANDLE_PEN_ALPHA   = 230
REGION_VOLUME_HANDLE_BRUSH_ALPHA = 200

REGION_VOLUME_MARKER_PIN_FILL     = DESELECTED_COLOR
REGION_VOLUME_MARKER_LINE_COLOR   = DESELECTED_COLOR
REGION_VOLUME_MARKER_LINE_ALPHA   = 200
REGION_VOLUME_MARKER_PIN_BORDER   = '#141414'
REGION_VOLUME_MARKER_TEXT_BG      = '#141414'
REGION_VOLUME_MARKER_TEXT_BG_ALPHA = 210
REGION_VOLUME_MARKER_TEXT_FG      = '#FFFFFF'

REGION_VOLUME_MARKER_PIN_R        = 5
REGION_VOLUME_MARKER_PIN_LINE_H   = 22
REGION_VOLUME_MARKER_TEXT_PAD     = 4
REGION_VOLUME_MARKER_BORDER_WIDTH = 1
REGION_VOLUME_MARKER_LINE_WIDTH   = 2

REGION_VOLUME_LABEL_OUTLINE_COLOR = '#000000'

REGION_VOLUME_MARKER_TEXT_SIZE    = 10
REGION_VOLUME_LABEL_TEXT_ALPHA_F  = 0.95

VOLUME_SHAPE_CUBE     = 'cube'
VOLUME_SHAPE_SPHERE   = 'sphere'
VOLUME_SHAPE_CYLINDER = 'cylinder'
VOLUME_SHAPE_CONE     = 'cone'
VOLUME_SHAPE_CAPSULE  = 'capsule'
VOLUME_SHAPE_TORUS    = 'torus'

VOLUME_SHAPE_POLYGON  = 'polygon'
VOLUME_SHAPES         = (
    VOLUME_SHAPE_CUBE, VOLUME_SHAPE_SPHERE, VOLUME_SHAPE_CYLINDER,
    VOLUME_SHAPE_CONE, VOLUME_SHAPE_CAPSULE, VOLUME_SHAPE_TORUS,
    VOLUME_SHAPE_POLYGON,
)
VOLUME_SHAPE          = 'cube'

VOLUME_SHAPE_RATIOS = {
    VOLUME_SHAPE_CUBE:     (1.0, 1.0, 1.0),
    VOLUME_SHAPE_SPHERE:   (1.0, 1.0, 1.0),
    VOLUME_SHAPE_CYLINDER: (1.0, 1.0, 1.0),
    VOLUME_SHAPE_CONE:     (1.0, 1.0, 1.0),
    VOLUME_SHAPE_TORUS:    (1.0, 1.0, 0.3),
    VOLUME_SHAPE_CAPSULE:  (0.375, 0.375, 1.0),
    VOLUME_SHAPE_POLYGON:  (1.0, 1.0, 1.0),
}

REGION_CENTER     = (0.0, 0.0, 0.0)
REGION_SIZE       = (1.0, 1.0, 1.0)
REGION_SOFTNESS   = 0.10

REGION_AUTOSIZE_ENABLE = True
REGION_AUTOSIZE_FACTOR = 1.0

UNIFORM_SCALE = True

REGION_SOFTNESS_RANGE = (0.0, 3.0)

REGION_COLOR              = DESELECTED_COLOR
REGION_HOVER_COLOR        = REGION_VOLUME_HOVER_COLOR

REGION_VOLUME_LOCK_COLOR  = LOCKED_COLOR

REGION_TRANSLATE_STEP = 0.1
REGION_SCALE_STEP     = 1.1

REGION_VOLUME_STRENGTH_DEFAULT = 1.0
REGION_VOLUME_STRENGTH_STEP    = 0.1
REGION_VOLUME_STRENGTH_MIN     = 0.1
REGION_VOLUME_STRENGTH_MAX     = 3.0

REGION_VOLUME_STARTUP_VISIBILITY = False

REGION_VOLUME_TOOL_DEFAULT = TOOL_TRANSLATE

REGION_VOLUME_KEY_VISIBLE        = 'H'
REGION_VOLUME_KEY_RESET          = 'Shift+R'
REGION_VOLUME_KEY_TOOL_TRANSLATE = 'W'
REGION_VOLUME_KEY_TOOL_ROTATE    = 'E'
REGION_VOLUME_KEY_TOOL_SCALE     = 'R'

REGION_VOLUME_KEY_CYCLE_SHAPE    = 'Y'

REGION_VOLUME_KEY_LOCK           = 'L'

REGION_VOLUME_KEY_HELP           = 'F2'

REGION_VOLUME_KEY_CONSOLE        = 'Ctrl+E'

REGION_VOLUME_KEY_ATTR           = 'Ctrl+A'

REGION_VOLUME_KEY_STRENGTH_UP    = 'Shift+Num+'
REGION_VOLUME_KEY_STRENGTH_DOWN  = 'Shift+Num-'
REGION_VOLUME_KEY_KEYFRAME_ADD    = 'Shift+A'
REGION_VOLUME_KEY_KEYFRAME_PREV   = 'Shift+PageUp'
REGION_VOLUME_KEY_KEYFRAME_NEXT   = 'Shift+PageDown'
REGION_VOLUME_KEY_KEYFRAME_REMOVE = 'Shift+D'
REGION_VOLUME_KEY_KEYFRAME_CLEAR  = 'Shift+Delete'

REGION_VOLUME_KEY_KEYFRAME_TOGGLE = 'Shift+P'

REGION_VOLUME_KEY_DELETE    = 'Ctrl+Shift+R'
REGION_VOLUME_KEY_DUPLICATE = 'Ctrl+Shift+D'

REGION_DUPLICATE_OFFSET_RATIO = 1.1

REGION_VOLUME_NUM_KEYS = (
    'Shift+1', 'Shift+2', 'Shift+3', 'Shift+4', 'Shift+5',
    'Shift+6', 'Shift+7', 'Shift+8', 'Shift+9',
)

REGION_VOLUME_LABEL_PIXEL_SIZE   = 13

REGION_VOLUME_LABEL_Y_OFFSET     = 6
REGION_VOLUME_LABEL_OUTLINE_ALPHA = 200

REGION_FILL_ON_SELECT_ONLY = True

REGION_VOLUME_KF_ANIM_DURATION = 100
REGION_VOLUME_KF_ANIM_FPS      = 60
REGION_VOLUME_KF_ANIM_EASING   = 'EasyEase'

